# Alternate pipeline that has proven to work better for bringing the footage to a format
# that lends itself better to ML-based annotation methods (i.e. DeepLabCut)
# File Paths
image_folder: "/Volumes/LaCie/Spyder_Vision/Habros_Day3_morning/Spider26_Habro15_gap45_gain20_AAAnorest"
flat_folder: "/Volumes/LaCie/Spyder_Vision/Flats_and_Darks/Flats_gap45_gain20"
output_name: "stride5_cropped_Spider26_Habro15_gap45_gain20_AAAnorest"

# Video Settings
vid_start_index: 0
num_images: 500
video_stride: 5
convert_to_gray: False
all_batches: True
crop: [
  [250,-1],
  [100,1600]
]

# Pipeline Stages
pipeline:
  [
    {
      name: mean_divide_video,
      params:
        [10],
      kwargs: {}
    },
    {
      name: summarize,
      params: [],
      kwargs: {}
    },    
    {
      name: block_match,
      params: [],
      kwargs: {}
    },
    {
      name: summarize,
      params: [],
      kwargs: {}
    },
    {
      name: sharpen,
      params: [],
      kwargs: {}
    },
    {
      name: adv_normalize,
      params: [1],
      kwargs: {}
    },
    {
      name: mul,
      params: [255],
      kwargs: {}
    },
    {
      name: summarize,
      params: [],
      kwargs: {}
    },
  ]